title: Tech Starter Kit
author: VLV
email: ipuser126@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Joined a New Software Company, me Too. So I have created this blog to share my learning Journey.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
